apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: pod-web
          image: garikoitz11/flask-notas
          ports:
            - containerPort: 5000